default: readme

readme:
  url: https://confluence.govdelivery.com
  page_id: 98141714
  filename: Readme.md
  notice: <h4>Notice - This file is sync'd with its git repo. Any changes will be lost.</h4>